### PR TITLE
docs(readme): add gastby-source-drupal config

### PR DESCRIPTION
**Pull request by luqven**
## Description

Updated [README](https://github.com/imgix/gatsby/blob/luis/drupalSource/README.md) to include gatsby-source-drupal configuration.

## Checklist: Fixing typos/Doc change

- [ ] The target branch is `beta`. This is important for our CI/CD config.
- [x] Each commit follows the conventional commit spec format: e.g. `chore(readme): fixed typo`. See the end of this file for more information.

### CODE REVIEW

**Review by frederickfogerty — CHANGES_REQUESTED** [review]
LGTM! Can we change the commit message to use `docs` rather than `chore`? Once that's done this is good to merge. Thanks!

**Comment by luqven** [comment]
Ah, sorry for the ping. Just realized you said "good to merge" 🤦🏼 .

**Comment by frederickfogerty** [comment]
@allcontributors-bot please add @luqven for documentation

**Comment by frederickfogerty** [comment]
@all-contributors please add @luqven for documentation

**Review by frederickfogerty — COMMENTED** [review]
✅ Cleaning up old reviews

**Pull request merged**
